### ISSUE TITLE
Stemming

### ISSUE THREAD

**Issue by MichalPitr** [donggyukimc/Inverse-cloze-task#1]
Hi, thanks for this repo. 

I have a question. By default, the text is stemmed before being passed to the transformer. This isn't usually done when training transformer networks, so could you explain whether there is some reasoning behind it? 

Thanks a lot! 
Michal

**Comment by donggyukimc** [comment]
Hi, Thank you for your interest.

In my code, stemming is only used to make inputs for TF-IDF retrieval.

It is because stemming usually boosts the performance token-based retrieval like TF-IDF.

As you can see, in data preprocessing, the tokenization results of two methods ( 1. nltk-stemming,  2. bert-tokenizer ) are generated for both question set and context (sentence) set.
https://github.com/donggyukimc/Inverse-cloze-task/blob/master/util.py#L58
https://github.com/donggyukimc/Inverse-cloze-task/blob/master/util.py#L68

1. nltk-stemming result is used for TF-IDF retrieval

2. bert-tokenizer result is used for Bert model inputs

Thanks

**Comment by MichalPitr** [comment]
Hi, thanks a lot for the explanation. 
I did not notice both methods were used independently, but this makes sense. 

Many thanks, 
Michal
